// Per-project facts, transcribed from HARVEST.md. Every number, name and
// address here is sourced — nothing invented. Where the source didn't state
// something (price, RERA, floor counts, etc.) the field is simply omitted;
// templates must never fill a gap with a guess.

const RESIDENTIAL = [
  {
    slug: 'sunrise',
    moodPlate: 'light-shadow',
    moodLine: 'Twenty-two homes, and a gymnasium, a community hall and a play area that belong to all of them.',
    name: 'Sunrise',
    kind: 'residential',
    status: 'Ongoing',
    tagline: '2BHK / 3BHK luxury flats in Bhagalpur',
    location: 'Bhagalpur, Bihar',
    address: 'At Chandi Prasad Lane, Near Anand Ram Dhandhania School, Bhagalpur, Bihar, India – 812002',
    description: 'Own a house in a locality away from the maddening traffic and frenzied activity of the city, close to everything green and clean. These 22 flats, breathtaking in ambiance, are a nature lover’s delight — a fully equipped gymnasium, community hall and children’s play area among the amenities.',
    unitSummary: '2BHK / 3BHK — 22 flats',
    areaTables: [{
      caption: 'Area Statement',
      rows: [
        ['A', '3BHK', '1,696 sqft'], ['B', '3BHK', '1,593 sqft'], ['C', '2BHK', '1,051 sqft'],
        ['D', '3BHK', '1,629 sqft'], ['E', '2BHK', '1,217 sqft'], ['F', '3BHK', '1,543 sqft'],
      ],
    }],
    amenities: ['Indoor children’s game room & gymnasium', 'Community hall', 'Pollution-free, peaceful surrounds', 'Sufficient water supply', 'Ample open area', 'School, court, hospital, hotels, ATM & bank nearby', '24-hour security with CCTV', 'Intercom', 'Heat-proofing treatment on terrace'],
    specifications: [
      { group: 'Structure & finish', text: 'Weather-proof paint over double-coat wall putty finish.' },
      { group: 'Water', text: '24-hour supply from an own deep tube well plus overhead tank.' },
      { group: 'Bath & kitchen', text: 'W.C. pans and washbasins with concealed hot/cold piping; granite kitchen slab with steel sink.' },
      { group: 'Fittings', text: 'ISI wire and modular switches; flush doors; aluminium sliding windows.' },
      { group: 'Common areas', text: 'Marble/granite/Kota finish; lift of Johnson/OTIS/Kone make; soundless generator backup.' },
      { group: 'Flooring', text: 'Vitrified tiles throughout.' },
    ],
    heroImage: '2-02-3.jpg',
    gallery: [],
    // sunrise-bgp-02-1.png was captioned "Typical Floor Plan" but is actually
    // the project's clip-art logo — dropped. 3-02.png is the genuine plan
    // (units A–F, sqft matching the area table above).
    floorPlans: [{ file: '3-02.png', caption: 'Typical Floor Plan' }],
    brochure: '/brochures/sunrise.pdf',
    notes: [],
  },
  {
    slug: 'tejprabharesidency',
    moodPlate: 'interior-warm',
    moodLine: 'Purnia, off the Lalganj road — a gated address built to stand through the shaking this land knows.',
    name: 'Tejprabha Residency',
    kind: 'residential',
    status: 'Ongoing',
    tagline: '2BHK / 3BHK apartments in Purnia',
    location: 'Purnia, Bihar',
    address: 'Tejprabha Residency, Newalal, Lalganj Road, Purnia, Bihar, India – 854303',
    description: 'An embodiment of world-class living and comfort, Tejprabha Residency is a high-end residential development housing spacious 2BHK and 3BHK flats, built to exemplary — and earthquake-resistant — construction standards. A fully integrated, extremely well-planned, ultra-modern gated community.',
    unitSummary: '2BHK / 3BHK',
    areaTables: [],
    amenities: ['Earthquake-resistant structure', 'Generator backup', 'Security cabin with intercom facility', 'Elegant designer entrance gate', 'Ample car parking', '24×7 water supply', 'State-of-the-art elevators', 'Rain water harvesting', 'Internal walls finished with smooth gypsum plaster'],
    specifications: [],
    heroImage: '2-02-1.jpg',
    gallery: [], // the only render is already the hero — don't repeat it below

    floorPlans: [{ file: '7-01-scaled-1.jpg', caption: 'Floor Plan' }],
    brochure: null,
    notes: ['Unit areas in sqft were not published for this project.'],
  },
  {
    slug: 'chandeshwar-apartment',
    moodPlate: 'stone-marble',
    moodLine: 'Granite underfoot, copper in the walls, and a frame engineered before a single flat was sold.',
    name: 'Chandeshwar Apartment',
    kind: 'residential',
    status: 'Ongoing',
    tagline: '2BHK / 3BHK luxury flats in Bhagalpur',
    location: 'Bhagalpur, Bihar',
    address: 'Chandeshwar Apartment, S.C. Banerjee Road, Behind Toposwi Hospital, Adampur Chowk, Bhagalpur – 812001',
    description: '',
    unitSummary: '2BHK / 3BHK',
    areaTables: [],
    amenities: [],
    specifications: [
      { group: 'Home', text: 'Earthquake-resistant frame; futuristic, well-ventilated elevation; Vastu-compliant flats; lit common areas; adequate water supply.' },
      { group: 'Kitchen', text: 'Granite-top platform, stainless-steel sink, designer tile dado above the platform.' },
      { group: 'Electrical', text: 'Concealed copper wiring; Havells or equivalent switches; TV/telephone points in living room and master bedroom; earth-leakage circuit breaker; DTH/EPBX provision.' },
      { group: 'Bathroom', text: 'Hot/cold mixer with overhead shower, branded CP fittings, concealed plumbing, anti-skid ceramic tiles.' },
      { group: 'Flooring', text: 'Vitrified tiles.' },
      { group: 'Doors & windows', text: 'Designer main door; powder-coated aluminium windows; designer balcony railing.' },
      { group: 'Utility', text: 'Washing-machine provision in the utility area; exhaust-fan provision in kitchen and toilets.' },
    ],
    heroImage: '0000_23_Chandeshwar_Apartment-05-01-2_11zon.jpg',
    gallery: ['Pi7_Image_chandeshwarapartmentnightview_page-00011.jpg'], // hero not repeated
    floorPlans: [{ file: 'New-Project-1.jpg', caption: 'Floor Plan & Views' }],
    brochure: '/brochures/chandeshwar-apartment.pdf',
    notes: ['No marketing description paragraph or unit-area table was published for this project.'],
  },
  {
    slug: 'keshavam-apartment',
    moodPlate: 'interior-warm',
    moodLine: 'Two blocks, nine floors, twelve ways to live in Deoghar — each measured to the square foot.',
    name: 'Keshavam Apartment',
    kind: 'residential',
    status: 'Ongoing',
    tagline: '2BHK / 3BHK luxury flats in Deoghar, Jharkhand',
    location: 'Deoghar, Jharkhand',
    address: 'Keshavam Apartment, In front of Khadi Gram Board Office, Jhousagarhi, Deoghar, Jharkhand – 814112',
    description: 'Two blocks of considered 2BHK and 3BHK homes, from the second to the ninth floor, with a full amenity set built around family life — play area, community hall, gymnasium and generator backup.',
    unitSummary: '2BHK / 3BHK across Block A & Block B, 2nd–9th floor',
    areaTables: [
      { caption: 'Block A — 2nd to 9th Floor', rows: [
        ['A-01', '3BHK', 'BUA 1,170 sqft / Saleable 1,560 sqft'],
        ['A-02', '2BHK', 'BUA 785 sqft / Saleable 1,045 sqft'],
        ['A-03', '3BHK', 'BUA 1,155 sqft / Saleable 1,540 sqft'],
        ['A-04', '3BHK', 'BUA 1,155 sqft / Saleable 1,540 sqft'],
        ['A-05', '2BHK', 'BUA 795 sqft / Saleable 1,060 sqft'],
        ['A-06', '3BHK', 'BUA 1,165 sqft / Saleable 1,555 sqft'],
      ] },
      { caption: 'Block B — 2nd to 9th Floor', rows: [
        ['B-01', '2BHK', 'BUA 935 sqft / Saleable 1,250 sqft'],
        ['B-02', '2BHK', 'BUA 940 sqft / Saleable 1,250 sqft'],
        ['B-03', '3BHK', 'BUA 1,390 sqft / Saleable 1,855 sqft'],
        ['B-04', '3BHK', 'BUA 1,485 sqft / Saleable 1,980 sqft'],
        ['B-05', '2BHK', 'BUA 865 sqft / Saleable 1,150 sqft'],
        ['B-06', '2BHK', 'BUA 905 sqft / Saleable 1,210 sqft'],
      ] },
    ],
    amenities: ['Indoor play/game area', 'Community hall', 'Gymnasium', 'Fire-fighting system', 'Intercom', 'Generator set', 'Rain water harvesting', 'Lift'],
    specifications: [
      { group: 'Structure', text: 'Earthquake-resistant frame; front/rear/side setbacks per bylaws; Vastu-compliant, futuristic elevation.' },
      { group: 'Common areas', text: 'Water-harvesting plant; designer false (POP) ceiling.' },
      { group: 'Fittings', text: 'Concealed copper wiring; Havells or equivalent switches; vitrified tile flooring; branded CP fittings; granite kitchen platform with steel sink.' },
    ],
    heroImage: '1.png',
    gallery: ['12.png', '15.png'], // hero (1.png) not repeated
    floorPlans: [{ file: '28.png', caption: 'Floor Plan — Block A' }, { file: '29.png', caption: 'Floor Plan — Block B' }],
    brochure: '/brochures/keshavam-apartment.pdf',
    notes: [],
  },
  {
    slug: 'ganesh-enclave',
    moodPlate: 'light-shadow',
    moodLine: 'Seventy-two homes off Mirzan Hat Road, a pool, a temple, and the market a short walk away.',
    name: 'Ganesh Enclave',
    kind: 'residential',
    status: 'Completed',
    tagline: '2BHK / 3BHK apartments in Bhagalpur',
    location: 'Sitla Asthan Chowk, Mirzan Hat Road, Bhagalpur',
    address: 'Sitla Asthan Chowk, Mirzan Hat Road, Bhagalpur',
    description: 'Away from the maddening traffic and frenzied activity of the city, close to everything green and clean. These 72 prestigious flats offer a swimming pool, landscaped gardens, a fully equipped gymnasium, community hall and children’s play area.',
    unitSummary: '2BHK / 3BHK — 72 flats',
    areaTables: [],
    amenities: ['24×7 security', 'Kids’ play area', 'Gated community', 'Swimming pool', 'Gymnasium', 'Lift', 'Temple', 'Community hall', '24×7 water supply'],
    specifications: [],
    locationPerks: ['Prime location at Sitla Asthan Chowk, Mirzan Hat Road', 'Upcoming flyover over Bholanath Bridge', 'Close to market and railway station', 'Easy access to banks, ATMs and hospitals'],
    extraContacts: [{ name: 'Rahul', phone: '+91 88772 22288' }, { name: 'Nitesh', phone: '+91 93343 83598' }],
    video: 'Ow-tuYvXo6c',
    heroImage: 'ganeshlogo.jpg',
    gallery: [],
    floorPlans: [{ file: 'ga1-680x700-1.jpg', caption: 'Site Plan' }, { file: 'gf1-700x676-1.jpg', caption: 'Floor Plan' }],
    brochure: '/brochures/ganesh-enclave.pdf',
    notes: ['The old site’s gallery repeated a single logo image; no distinct set of elevation photographs exists in the harvest for this project.'],
  },
  {
    slug: 'shivalaya',
    moodPlate: 'stone-marble',
    moodLine: 'Named for the abode of Shiva, built in the temple town itself — a rooftop above, Deoghar below.',
    name: 'Shivalaya',
    kind: 'residential',
    status: 'Completed',
    tagline: '2BHK / 3BHK flats in Deoghar',
    location: 'Deoghar, Jharkhand',
    address: 'Raghunath Road, Behind Prabhat Khabar Office, Jhounsagarhi, Deoghar – 814152',
    description: 'Shivalaya, as the name suggests, is an incarnation of the divine and serenity. A master-planned gated community bestowed with the qualities of an urban lifestyle, at the heart of Deoghar.',
    unitSummary: '2BHK / 3BHK',
    areaTables: [{
      caption: 'Unit Areas',
      rows: [['Flat A', '3BHK', '1,375 sqft'], ['Flat B', '2BHK', '1,069 sqft'], ['Flat C', '2BHK', '975 sqft'], ['Flat D', '3BHK', '1,638 sqft']],
    }],
    amenities: ['Well-appointed modern homes with sunshine and ventilation', 'Rooftop clubhouse with indoor games', 'State-of-the-art gymnasium', 'Prime location near bus stop, temples and hotels', '24-hour generator backup', 'Fire-fighting system', '24-hour CCTV surveillance'],
    specifications: [
      { group: 'Structure', text: 'RCC framed structure; vitrified tile flooring; anti-skid ceramic toilet flooring.' },
      { group: 'Fittings', text: 'Hot/cold mixer showers; granite kitchen platform with steel sink; aluminium sliding windows.' },
      { group: 'Services', text: 'Automatic passenger lifts; intercom facility; round-the-clock trained security.' },
    ],
    heroImage: 'hero-monument-clean.jpg',
    gallery: [],
    floorPlans: [
      { file: 'flat-A.jpg', caption: 'Flat A' }, { file: 'Flat-B.jpg', caption: 'Flat B' },
      { file: 'Flat-C.jpg', caption: 'Flat C' }, { file: 'Flat-D.jpg', caption: 'Flat D' },
      { file: 'FloorPlan_Shivalaya.jpg', caption: 'Typical Floor Plan' },
    ],
    brochure: '/brochures/shivalaya.pdf',
    notes: ['The old site listed two conflicting addresses for this project (a Bhagalpur one duplicated from Jagdish Enclave, and a Deoghar one matching the body copy). The Deoghar address is shown here as the more plausible of the two — needs client confirmation.'],
  },
  {
    slug: 'annapurna-heights',
    moodPlate: 'interior-warm',
    moodLine: 'Kolkata, in two blocks — where a lift by KONE and a point for the air-conditioner were decided early.',
    name: 'Annapurna Heights',
    kind: 'residential',
    status: 'Completed',
    tagline: '2BHK / 3BHK luxury flats in Kolkata',
    location: 'Kolkata, West Bengal',
    address: '8 Naya Patti Road, Plaza Tower Complex, Block-D-2, 4th Floor, R.N-9, Kolkata – 700055, West Bengal, India',
    description: 'Imagine a life where the world revolves around you — where the city and everything you need surrounds you, amidst a nature-soaked environment with 24×7 security for your family.',
    unitSummary: '2BHK / 3BHK across Block 1 & Block 2, 1st–4th floor',
    areaTables: [
      { caption: 'Block 1 — Typical 1st to 4th Floor', rows: [
        ['A', '3BHK', '1,469 sqft'], ['B', '2BHK', '1,006 sqft'], ['C', '3BHK', '1,538 sqft'],
        ['D', '3BHK', '1,438 sqft'], ['E', '2BHK', '1,006 sqft'], ['F', '3BHK', '1,644 sqft'],
      ] },
      { caption: 'Block 2 — Typical 1st to 4th Floor', rows: [
        ['G', '3BHK', '1,469 sqft'], ['H', '2BHK', '1,006 sqft'], ['I', '3BHK', '1,538 sqft'],
        ['J', '3BHK', '1,438 sqft'], ['K', '2BHK', '1,006 sqft'], ['L', '3BHK', '1,644 sqft'],
      ] },
    ],
    amenities: ['Elegant designer entrance with security cabin', 'Community hall cum gymnasium on the roof', 'Designer entrance foyer & guard room', 'Generator backup for apartments, lifts and common areas', 'Earthquake-resistant structure', 'Intercom facility', 'CCTV surveillance', 'Fire-fighting system', 'Ample car & two-wheeler parking'],
    specifications: [
      { group: 'Structure', text: 'RCC framed structure with raft foundation; vitrified tile / marble common-area flooring.' },
      { group: 'Fittings', text: 'Black granite kitchen platform; A.C. point in all bedrooms and living room; KONE/OTIS elevators.' },
      { group: 'Finish', text: 'High-quality exterior paint over double-coat white putty interior.' },
    ],
    heroImage: 'annapurna-hero-clean.jpg',
    gallery: ['Pi7_Image_AnnapurnaHeights_page-0002.jpg', 'Pi7_Image_AnnapurnaHeights_page-0008.jpg', 'Pi7_Image_AnnapurnaHeights_page-00061.jpg'],
    floorPlans: [{ file: 'Block-1-1.jpg', caption: 'Floor Plan — Block 1' }, { file: 'Block-2-2.jpg', caption: 'Floor Plan — Block 2' }],
    brochure: '/brochures/annapurna-heights.pdf',
    notes: ['This is the only project in the harvest located outside Bihar/Jharkhand — worth confirming with the client that it is current.'],
  },
  {
    slug: 'jagdish-enclave',
    moodPlate: 'light-shadow',
    moodLine: 'Ground and five floors near Chanakya Vihar, with servant quarters, a top-floor gym and cross-ventilation throughout.',
    name: 'Jagdish Enclave',
    kind: 'residential',
    status: 'Completed',
    tagline: '2BHK / 3BHK flats in Bhagalpur',
    location: 'Near Chanakya Vihar Colony, Bhagalpur',
    address: 'Chanakya Vihar Colony, Bhagalpur – 812002',
    description: 'A project made from elegantly created 2 and 3BHK flats — a quality home with premium specifications in a pollution-free environment, at one of Bhagalpur’s most sought-after and prestigious locations.',
    unitSummary: '2BHK / 3BHK, Ground + 5 floors',
    areaTables: [
      { caption: 'Ground Floor Plan', rows: [['A', '3BHK', '1,772 sqft'], ['B', '2BHK', '1,240 sqft'], ['C', '2BHK', '1,210 sqft'], ['D', '3BHK', '1,524 sqft']] },
      { caption: '1st to 5th Floor Plan', rows: [
        ['A', '3BHK', '1,772 sqft'], ['B', '2BHK', '1,240 sqft'], ['C', '3BHK', '1,210 sqft'], ['D', '3BHK', '1,524 sqft'],
        ['E', '3BHK', '1,280 sqft'], ['F', '3BHK', '1,376 sqft'], ['G', '3BHK', '1,280 sqft'], ['H', '3BHK', '1,498 sqft'],
      ] },
    ],
    amenities: ['Elegant designer entrance gate with security cabin', 'Community hall with kitchen (ground floor)', 'State-of-the-art gymnasium (top floor)', 'Children’s play area', 'Generator backup for apartments, lifts and common areas', 'Earthquake-resistant structure', 'Internal paved road', 'Intercom facility', 'Rain water harvesting', 'Fire-fighting system', 'Manual elevators', 'Internal walls finished with smooth gypsum plaster', 'Tiles flooring in common areas', 'Ample car & two-wheeler parking', 'Separate servant quarters', '24-hour CCTV surveillance', 'Cross-ventilated flats'],
    specifications: [],
    heroImage: 'Jagdish-enclave-1-img_page-0001.jpg',
    gallery: [], // the only render is already the hero — don't repeat it below

    floorPlans: [
      { file: 'Untitled-1-17_19_11zon.jpg', caption: 'Ground Floor Plan' },
      { file: 'Untitled-1-18_18_11zon.jpg', caption: '1st to 5th Floor Plan' },
      { file: 'Untitled-1-17-1_16_11zon.jpg', caption: 'Unit A — 3BHK, 1,772 sqft' },
      { file: 'Untitled-1-18.jpg', caption: 'Unit B — 2BHK, 1,240 sqft' },
      { file: 'Untitled-1-17-1.jpg', caption: 'Unit C — 2BHK, 1,210 sqft' },
      { file: 'Untitled-1-18-1.jpg', caption: 'Unit D — 3BHK, 1,524 sqft' },
      { file: 'Untitled-1-18-3.jpg', caption: 'Unit E — 3BHK, 1,280 sqft' },
      { file: 'Untitled-1-17-2.jpg', caption: 'Unit F — 3BHK, 1,376 sqft' },
      { file: 'Untitled-1-18-3-1.jpg', caption: 'Unit G — 3BHK, 1,280 sqft' },
      // the source states two conflicting areas for Unit H (1,280 vs 1,498 sqft) — caption omits the figure
      { file: 'UNIT-H.jpg', caption: 'Unit H — 3BHK' },
    ],
    brochure: '/brochures/jagdish-enclave.pdf',
    notes: ['Shown as "Completed" matching the old site’s navigation; that site’s own body copy described flats as still "coming up" for possession — true status still needs client confirmation.', 'Two of the harvested hero images for this project were filenamed as stock photography rather than site photography — the aerial/day image used here is the one that reads as a genuine project render.'],
  },
];

const HOSPITALITY = [
  {
    slug: 'chinmaye-in',
    name: 'Hotel Chinmaye Inn',
    kind: 'hospitality',
    status: 'Open',
    tagline: 'A sister property in hospitality, Bhagalpur',
    location: 'Bhagalpur, Bihar',
    address: 'Rai Bahadur Sukhraj Rai Road, Katahalbari, Khanjarpur, Bhagalpur, Bihar 812001',
    description: 'Vikramshila Developers’ hospitality venture in Bhagalpur — a multi-cuisine restaurant, wedding and event hosting, and rooms across three tiers, minutes from the city’s landmarks.',
    rooms: [
      { type: 'Presidential Suite', single: '₹7,499', double: '₹7,499', extra: '₹600' },
      { type: 'Deluxe Suite', single: '₹4,000', double: '₹5,000', extra: '₹600' },
      { type: 'Business Class Room', single: '₹2,200', double: '₹3,500', extra: '₹600' },
    ],
    roomsNote: 'Tariffs stated as per-night, government taxes as applicable.',
    facilities: ['Multi-cuisine restaurant, from world cuisine to authentic Italian and Indian fare', 'Wedding coordination', 'Music & dancing — DJ, live band, solo artist, anchor', '2-wheeler and 4-wheeler parking'],
    testimonials: [
      { name: 'Ayush Khetriwal', role: 'Businessman', quote: 'Hand down, this is the best place to stay in Bhagalpur. It’s an icon on its own. The best part is the hospitality and food — the owners show a keen interest in your comfort.' },
      { name: 'Ayush Khetriwal', role: 'Businessman', quote: 'Easy to find location on the main road, beautiful new building, smooth and fast check-in… big well-lighted room, comfortable bed… fast room service, polite staff, 24 hours hot water… This is perhaps the best hotel of the city.' },
      { name: 'Kamlesh Rawani', role: 'Businessman', quote: 'It was a nice experience staying at Chinmaye Inn. This hotel has all the amenities. Service is very good and staff are very cooperative — the most important part is the ambience, and a beautiful rooftop restaurant.' },
    ],
    phone: '+91 88772 22233',
    email: 'info@chinmaye.in',
    mapEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3608.426357196371!2d86.99307541451124!3d25.25623918386872!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sChinmaye%20Inn!5e0!3m2!1sen!2sin',
    heroImage: 'chinmayePng-scaled-1.jpg',
    // about_img_chinmaye.jpg removed: it is a stock photograph the old site used,
    // not the actual hotel — showing it as the property would be a lie
    gallery: ['Pi7_Image_DSC_3510.jpg', 'Pi7_Image_DSC_3565.jpg', 'Pi7_Image_DSC_3576.jpg'],
    notes: [],
  },
];

// Named on the old site with no detail page, photography or unit data —
// promoted to full index rows (unlinked) so no development goes unlisted.
// Astha Garden's status is genuinely unstated in the source; left blank.
const STUBS = [
  { name: 'Devpreet Vikramshila', location: 'Jharkhand', status: 'Completed', unitSummary: '2BHK / 3BHK' },
  { name: 'Shyamri Tower', location: '', status: 'Completed', unitSummary: '2BHK / 3BHK' },
  { name: 'Astha Garden', location: 'Jharkhand', status: '', unitSummary: '2BHK / 3BHK' },
];

module.exports = { RESIDENTIAL, HOSPITALITY, STUBS, ALL: RESIDENTIAL.concat(HOSPITALITY) };
